/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nick' at '12/22/16 9:01 AM' with Gradle 3.2.1
 *
 * @author nick, @date 12/22/16 9:01 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
